name: CI

on: [push, pull_request]

jobs:
  build:
    # Perform a generic build in case of any critical errors
    name: Build
    runs-on: ubuntu-20.04
    steps:
    # Checks out under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get GTK Version
      run: |
        source PKGBUILD
        echo "GTK_VERSION=${_gtkver}" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        echo "deb-src http://gb.archive.ubuntu.com/ubuntu/ focal main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get build-dep gtk+3.0
        sudo apt-get install quilt sassc meson ninja-build cmake
        sudo apt-get install libgif-dev libelf-dev

    - name: Cache GTK Source
      uses: actions/cache@v2
      id: gtksrc
      with:
        path: 'gtk+*.tar.xz'
        key: gtk-${{ env.GTK_VERSION }}

    - name: Download GTK Source
      if: steps.gtksrc.outputs.cache-hit != 'true'
      run: |
        source PKGBUILD
        wget https://download.gnome.org/sources/gtk+/${pkgver%.*}/gtk+-${_gtkver}.tar.xz

    - name: Extract GTK Source
      run: |
        source PKGBUILD
        tar -xJf gtk+*.tar.xz

    # Uses PKGBUILD prepare() directly
    - name: Apply Patches
      run: |
        source PKGBUILD
        srcdir="$(pwd)"
        prepare

    # Based on PKGBUILD build()
    # Build system may connect to GNOME's GitLab to retrieve glib dependency
    - name: Build
      run: |
        source PKGBUILD
        CFLAGS+=" -DG_ENABLE_DEBUG -DG_DISABLE_CAST_CHECKS"
        meson gtk+-${_gtkver} build \
            -D broadway_backend=true \
            -D colord=no \
            -D demos=true \
            -D examples=false \
            -D tests=false \
            -D installed_tests=false
        ninja -C build

  makepkg:
    # Create artifacts for the Arch packages for convenient testing, and to
    # validate the package integrity with changes.
    name: 'Package / Arch'
    runs-on: ubuntu-latest
    steps:
    # Checks out under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get GTK Version
      run: |
        source PKGBUILD
        echo "GTK_VERSION=${_gtkver}" >> $GITHUB_ENV

    - name: Cache GTK Source
      uses: actions/cache@v2
      id: gtksrc
      with:
        path: 'gtk+*.tar.xz'
        key: gtk-${{ env.GTK_VERSION }}

    - name: Generate Checksum
      run: |
        cp PKGBUILD PKGBUILD.before
        md5sum PKGBUILD >> PKGBUILD.md5

    - name: Validate Package
      run: |
        # makepkg cannot run as root
        sudo chown -R nobody .

        # Start Arch using Docker
        docker run -d -t -v $GITHUB_WORKSPACE:/workspace --name archlinux archlinux:base-devel
        docker exec archlinux pacman -Sy --noconfirm namcap

        # Validate the PKGBUILD is the same and free from errors
        docker exec --workdir=/workspace --user nobody archlinux makepkg --geninteg
        docker exec --workdir=/workspace --user nobody archlinux namcap -i PKGBUILD

        # Stop containers
        docker stop archlinux -t 1
        docker rm archlinux

    - name: Verify Checksum
      run: |
        echo "If this fails, the PKGBUILD needs updating"
        diff PKGBUILD.before PKGBUILD
        md5sum -c PKGBUILD.md5

    - name: 'Upload Artifact: gtk3-classic'
      uses: actions/upload-artifact@v2
      with:
        name: gtk3-classic-run${{github.run_number}}-pkg
        path: gtk3-classic-*.pkg*

    - name: 'Upload Artifact: lib32-gtk3-classic'
      uses: actions/upload-artifact@v2
      with:
        name: lib32-gtk3-classic-run${{github.run_number}}-pkg
        path: lib32-gtk3-classic-*.pkg*
