name: CI

on: [push, pull_request]

jobs:
  check_series:
    name: 'Check / Series'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check series file
      run: |
        for patch in $(ls *.patch); do
            if ! grep "$patch" series; then
                echo "::error title=$patch::Patch is missing from series file"
                exit 1
            fi
        done

  build:
    # Perform a generic build in case of any critical errors
    name: Build
    runs-on: ubuntu-22.04
    needs: [check_series]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get GTK Version
      run: |
        source PKGBUILD
        echo "GTK_VERSION=${_gtkver}" >> $GITHUB_ENV

    - name: Cache GTK source
      uses: actions/cache@v4
      id: gtksrc
      with:
        path: 'gtk*.tar.gz'
        key: gtk-${{ env.GTK_VERSION }}

    - name: Download GTK source
      if: steps.gtksrc.outputs.cache-hit != 'true'
      run: |
        source PKGBUILD
        wget "https://gitlab.gnome.org/GNOME/gtk/-/archive/${_gtkver}/gtk-${_gtkver}.tar.gz"

    - name: Extract GTK source
      run: |
        source PKGBUILD
        tar -xzf gtk*.tar.gz

    - name: Install Dependencies
      run: |
        echo "deb-src http://gb.archive.ubuntu.com/ubuntu/ focal main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get build-dep gtk+3.0
        sudo apt-get install quilt sassc meson ninja-build cmake
        sudo apt-get install libgif-dev libelf-dev

    # Uses PKGBUILD prepare() directly
    - name: Apply Patches
      run: |
        source PKGBUILD
        srcdir="$(pwd)"
        prepare

    # Uses PKGBUILD build() directly
    # Build system may connect to GNOME's GitLab to retrieve glib dependency
    - name: Build
      run: |
        source PKGBUILD
        arch-meson() { meson "$@"; }
        build

  makepkg:
    # Create artifacts for the Arch packages for convenient testing
    name: 'Package / Arch'
    runs-on: ubuntu-latest
    needs: [check_series]
    steps:
    # Checks out under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get GTK Version
      run: |
        source PKGBUILD
        echo "GTK_VERSION=${_gtkver}" >> $GITHUB_ENV

    - name: Cache GTK Source
      uses: actions/cache@v4
      id: gtksrc
      with:
        path: 'gtk*.tar.gz'
        key: gtk-${{ env.GTK_VERSION }}

    - name: Cache Pacman Packages
      uses: actions/cache@v4
      env:
        cache-name: pacman-cache
      with:
        path: ~/pacman-cache
        key: pacman-cache

    - name: Start Arch Linux
      run: |
        # Start and update Arch Linux within a Docker container
        docker run --privileged -d -t -v ~/pacman-cache/pkg:/var/cache/pacman/pkg -v $GITHUB_WORKSPACE:/workspace --name archlinux archlinux:base-devel
        docker exec archlinux pacman -Syu --noconfirm namcap

        # Add user
        docker exec archlinux useradd builder
        docker exec archlinux /bin/bash -c "echo 'builder ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers"

        # Use as a reference when validating PKGBUILD
        cp PKGBUILD PKGBUILD.before
        md5sum PKGBUILD >> PKGBUILD.md5

        # This 'builder' user will take directory ownership
        docker exec archlinux chown -R builder /workspace

    - name: Validate PKGBUILD
      run: |
        # Validate the PKGBUILD - these commands modify the file
        docker exec --workdir=/workspace --user builder archlinux makepkg --geninteg
        docker exec --workdir=/workspace --user builder archlinux namcap -i PKGBUILD

        # Inform the user if changes need to be made
        md5sum -c PKGBUILD.md5 || (echo -e "\nTo fix, please push a commit with the following changes to the PKGBUILD file.\nHere's the patch:\n" && diff -u PKGBUILD.before PKGBUILD)

    - name: Make Package
      run: |
        docker exec --workdir=/workspace --user builder archlinux makepkg -s --noconfirm

    - name: Stop Arch Linux
      run: |
        docker stop archlinux -t 1
        docker rm archlinux

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: gtk3-classic-run${{github.run_number}}-pkg
        path: gtk3-classic-*.pkg*
